name: reveal-secrets
on:
  push:
    branches:
      - main
      - production
  pull_request:


jobs:
  reveal-secrets:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Show the secret
        run: |
          echo "Super secret value: ${{ secrets.SUPER_SECRET_VALUE }}"

